---
swagger: "2.0"
info:
  description: "Ejemplo básico de API que permite la gestión mínima de una cuenta."
  version: "1.0.0"
  title: "Cuentas"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "cristobal.sepulveda@bbva.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v2"
tags:
- name: "cuentas"
  description: "Gestión de una cuenta"
  externalDocs:
    description: "Más info"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /cuentas:
    post:
      tags:
      - "cuentas"
      summary: "Crear una cuenta nueva"
      description: ""
      operationId: "crearCuenta"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto con toda la información necesaria para la creación de\
          \ una cuenta."
        required: true
        schema:
          $ref: "#/definitions/Cuenta"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Cuentas"
    put:
      tags:
      - "cuentas"
      summary: "Modificar una cuenta existente."
      description: ""
      operationId: "modificaCuenta"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Objeto con los datos de la cuenta a modificar."
        required: true
        schema:
          $ref: "#/definitions/Cuenta"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Cuenta no encontrada."
        405:
          description: "Validation exception"
      x-swagger-router-controller: "Cuentas"
  /cuentas/{cuentaId}:
    get:
      tags:
      - "cuentas"
      summary: "Devolver los datos de una cuenta"
      description: "Dado el identificador de una cuenta de vuelve todos sus datos."
      operationId: "infoCuenta"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "cuentaId"
        in: "path"
        description: "Id de la cuenta a consultar"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cuenta"
        400:
          description: "Identificador de cuenta inválido"
      x-swagger-router-controller: "Cuentas"
    delete:
      tags:
      - "cuentas"
      summary: "Eliminar una cuenta"
      description: ""
      operationId: "eliminarCuenta"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "cuentaId"
        in: "path"
        description: "Id de la cuenta a eliminar"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "El id proporcionado es incorrecto."
        404:
          description: "Cuenta no encontrada."
      x-swagger-router-controller: "Cuentas"
definitions:
  Cuenta:
    type: "object"
    properties:
      cuentaId:
        type: "integer"
        format: "int64"
      cliente:
        type: "integer"
        format: "int64"
      saldo:
        type: "string"
        format: "int64"
      movimientos:
        type: "array"
        items:
          $ref: "#/definitions/Movimiento"
    example:
      cliente: 6
      cuentaId: 0
      saldo: "saldo"
      movimientos:
      - fecha: "2000-01-23"
        id: 1
        saldo: 5.962133916683182377482808078639209270477294921875
      - fecha: "2000-01-23"
        id: 1
        saldo: 5.962133916683182377482808078639209270477294921875
    xml:
      name: "Cuenta"
  Movimiento:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      fecha:
        type: "string"
        format: "date"
      saldo:
        type: "number"
        format: "double"
    example:
      fecha: "2000-01-23"
      id: 1
      saldo: 5.962133916683182377482808078639209270477294921875
    xml:
      name: "Movimiento"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
